// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-rc.1
// 	protoc        v3.21.5
// source: data.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @gogs:Components
type Components struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseWorld *BaseWorld `protobuf:"bytes,1,opt,name=BaseWorld,proto3" json:"BaseWorld,omitempty"`
}

func (x *Components) Reset() {
	*x = Components{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Components) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Components) ProtoMessage() {}

func (x *Components) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Components.ProtoReflect.Descriptor instead.
func (*Components) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *Components) GetBaseWorld() *BaseWorld {
	if x != nil {
		return x.BaseWorld
	}
	return nil
}

type BaseWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// join the world
	JoinWorld *JoinWorld `protobuf:"bytes,1,opt,name=JoinWorld,proto3" json:"JoinWorld,omitempty"`
	// return the join world response
	JoinWorldSuccess *JoinWorldSuccess `protobuf:"bytes,2,opt,name=JoinWorldSuccess,proto3" json:"JoinWorldSuccess,omitempty"`
	// notifiy other player someone join the world
	JoinWorldNotifiy *JoinWorldNotifiy `protobuf:"bytes,3,opt,name=JoinWorldNotifiy,proto3" json:"JoinWorldNotifiy,omitempty"`
	// update user position and rotation to other player
	UpdateUserInWorld *UpdateUserInWorld `protobuf:"bytes,4,opt,name=UpdateUserInWorld,proto3" json:"UpdateUserInWorld,omitempty"`
	// leave the world and notify other player
	LeaveWorldNotifiy *LeaveWorldNotifiy `protobuf:"bytes,5,opt,name=LeaveWorldNotifiy,proto3" json:"LeaveWorldNotifiy,omitempty"`
}

func (x *BaseWorld) Reset() {
	*x = BaseWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseWorld) ProtoMessage() {}

func (x *BaseWorld) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseWorld.ProtoReflect.Descriptor instead.
func (*BaseWorld) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *BaseWorld) GetJoinWorld() *JoinWorld {
	if x != nil {
		return x.JoinWorld
	}
	return nil
}

func (x *BaseWorld) GetJoinWorldSuccess() *JoinWorldSuccess {
	if x != nil {
		return x.JoinWorldSuccess
	}
	return nil
}

func (x *BaseWorld) GetJoinWorldNotifiy() *JoinWorldNotifiy {
	if x != nil {
		return x.JoinWorldNotifiy
	}
	return nil
}

func (x *BaseWorld) GetUpdateUserInWorld() *UpdateUserInWorld {
	if x != nil {
		return x.UpdateUserInWorld
	}
	return nil
}

func (x *BaseWorld) GetLeaveWorldNotifiy() *LeaveWorldNotifiy {
	if x != nil {
		return x.LeaveWorldNotifiy
	}
	return nil
}

type JoinWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinWorld) Reset() {
	*x = JoinWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorld) ProtoMessage() {}

func (x *JoinWorld) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorld.ProtoReflect.Descriptor instead.
func (*JoinWorld) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

// @gogs:ServerMessage
type JoinWorldSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uids []string `protobuf:"bytes,2,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *JoinWorldSuccess) Reset() {
	*x = JoinWorldSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinWorldSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldSuccess) ProtoMessage() {}

func (x *JoinWorldSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldSuccess.ProtoReflect.Descriptor instead.
func (*JoinWorldSuccess) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *JoinWorldSuccess) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *JoinWorldSuccess) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

// @gogs:ServerMessage
type JoinWorldNotifiy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *JoinWorldNotifiy) Reset() {
	*x = JoinWorldNotifiy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinWorldNotifiy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldNotifiy) ProtoMessage() {}

func (x *JoinWorldNotifiy) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldNotifiy.ProtoReflect.Descriptor instead.
func (*JoinWorldNotifiy) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *JoinWorldNotifiy) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UpdateUserInWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Postion  *Vecotr3  `protobuf:"bytes,2,opt,name=postion,proto3" json:"postion,omitempty"`
	Rotation *Rotation `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
}

func (x *UpdateUserInWorld) Reset() {
	*x = UpdateUserInWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserInWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInWorld) ProtoMessage() {}

func (x *UpdateUserInWorld) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInWorld.ProtoReflect.Descriptor instead.
func (*UpdateUserInWorld) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserInWorld) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdateUserInWorld) GetPostion() *Vecotr3 {
	if x != nil {
		return x.Postion
	}
	return nil
}

func (x *UpdateUserInWorld) GetRotation() *Rotation {
	if x != nil {
		return x.Rotation
	}
	return nil
}

// @gogs:ServerMessage
type LeaveWorldNotifiy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *LeaveWorldNotifiy) Reset() {
	*x = LeaveWorldNotifiy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveWorldNotifiy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveWorldNotifiy) ProtoMessage() {}

func (x *LeaveWorldNotifiy) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveWorldNotifiy.ProtoReflect.Descriptor instead.
func (*LeaveWorldNotifiy) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveWorldNotifiy) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Vecotr3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vecotr3) Reset() {
	*x = Vecotr3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vecotr3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vecotr3) ProtoMessage() {}

func (x *Vecotr3) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vecotr3.ProtoReflect.Descriptor instead.
func (*Vecotr3) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{7}
}

func (x *Vecotr3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vecotr3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vecotr3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Rotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W float32 `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
}

func (x *Rotation) Reset() {
	*x = Rotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rotation) ProtoMessage() {}

func (x *Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rotation.ProtoReflect.Descriptor instead.
func (*Rotation) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{8}
}

func (x *Rotation) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rotation) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rotation) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Rotation) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

var File_data_proto protoreflect.FileDescriptor

var file_data_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x3c, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x2e, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x09, 0x42, 0x61, 0x73, 0x65, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x22, 0xd5, 0x02, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12,
	0x2e, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x57,
	0x6f, 0x72, 0x6c, 0x64, 0x52, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12,
	0x43, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x43, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x79, 0x52, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x79, 0x12, 0x46, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x12, 0x46, 0x0a, 0x11, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x79, 0x52, 0x11, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x79, 0x22, 0x0b, 0x0a, 0x09, 0x4a, 0x6f, 0x69,
	0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x38, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73,
	0x22, 0x24, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x7c, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x28, 0x0a,
	0x07, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x56, 0x65, 0x63, 0x6f, 0x74, 0x72, 0x33, 0x52, 0x07,
	0x70, 0x6f, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x11, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x07, 0x56,
	0x65, 0x63, 0x6f, 0x74, 0x72, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a,
	0x22, 0x42, 0x0a, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x77, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData = file_data_proto_rawDesc
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_proto_rawDescData)
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_data_proto_goTypes = []interface{}{
	(*Components)(nil),        // 0: model.Components
	(*BaseWorld)(nil),         // 1: model.BaseWorld
	(*JoinWorld)(nil),         // 2: model.JoinWorld
	(*JoinWorldSuccess)(nil),  // 3: model.JoinWorldSuccess
	(*JoinWorldNotifiy)(nil),  // 4: model.JoinWorldNotifiy
	(*UpdateUserInWorld)(nil), // 5: model.UpdateUserInWorld
	(*LeaveWorldNotifiy)(nil), // 6: model.LeaveWorldNotifiy
	(*Vecotr3)(nil),           // 7: model.Vecotr3
	(*Rotation)(nil),          // 8: model.Rotation
}
var file_data_proto_depIdxs = []int32{
	1, // 0: model.Components.BaseWorld:type_name -> model.BaseWorld
	2, // 1: model.BaseWorld.JoinWorld:type_name -> model.JoinWorld
	3, // 2: model.BaseWorld.JoinWorldSuccess:type_name -> model.JoinWorldSuccess
	4, // 3: model.BaseWorld.JoinWorldNotifiy:type_name -> model.JoinWorldNotifiy
	5, // 4: model.BaseWorld.UpdateUserInWorld:type_name -> model.UpdateUserInWorld
	6, // 5: model.BaseWorld.LeaveWorldNotifiy:type_name -> model.LeaveWorldNotifiy
	7, // 6: model.UpdateUserInWorld.postion:type_name -> model.Vecotr3
	8, // 7: model.UpdateUserInWorld.rotation:type_name -> model.Rotation
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Components); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinWorldSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinWorldNotifiy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserInWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveWorldNotifiy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vecotr3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_rawDesc = nil
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
